# .travis.yml file

language: python

install:
    - pip install pytest pytest-cov
    - pip install coveralls

install:
  - python setup.py install

script:
    - py.test id_analyses/test/ -v --cov=id_analyses --cov-report term-missing

after_script:
     - coveralls
