# .travis.yml file

language: python

install:
    - pip install pytest pytest-cov
    - pip install coveralls
    - python setup.py install

script:
    - py.test id_tools/test/ -v --cov=id_tools --cov-report term-missing

after_script:
    - coveralls
