# .travis.yml file
cache: apt
sudo: true
language: python
python: 
    - "2.7"
    
addons:
    apt:
        packages:
        - libhdf5-serial-dev

install:
    - pip install pytest pytest-cov
    - pip install coveralls
    - python setup.py install

script:
    - py.test test --cov=id_analyses

after_script:
    - coveralls
    