# .travis.yml file

language: python

install:
    - python setup.py install
    - pip install pytest pytest-cov
    - pip install coveralls

script:
    - py.test --cov=src

after_success:
     - coveralls
